#!/bin/bash -x

# Save the build artifacts used by downstream jobs for publishing the nightly build.
# Creates a single file jenkins-artifacts.tgz containing everything

rm -rf jenkins-artifacts jenkins-artifacts.tgz

mkdir jenkins-artifacts


# publish-nightly publishes scaladoc, distribution archives
[[ -d build/scaladoc ]] && {
  mkdir -p jenkins-artifacts/build
  rsync -rlv build/scaladoc jenkins-artifacts/build/
}
[[ -d dists/archives ]] && {
  mkdir -p jenkins-artifacts/dists
  rsync -rlv dists/archives jenkins-artifacts/dists/
}
#[[ -d dists/sbaz ]] && {
#  mkdir -p jenkins-artifacts/dists
#  rsync -rlv dists/sbaz jenkins-artifacts/dists/
#}

# publish-nightly publishes maven artifacts
[[ -d dists/maven ]] && {
  mkdir -p jenkins-artifacts/dists
  rsync -rlv dists/maven jenkins-artifacts/dists/
}

# scala-nightly-signatures checks signatures of scala-library.jar
[[ -e dists/latest/lib/scala-library.jar ]] && {
  mkdir -p jenkins-artifacts/dists/latest/lib
  cp dists/latest/lib/scala-library.jar jenkins-artifacts/dists/latest/lib/scala-library.jar
}

tar czf jenkins-artifacts.tgz jenkins-artifacts
rm -rf jenkins-artifacts
