#!/bin/bash -x

scriptsDir="$( cd "$( dirname "$0" )" && pwd )"
. $scriptsDir/common

# Publishes nightly build to rsync_dest

[[ $# -eq 1 ]] || {
  cat <<EOM
Usage: $0 <branch>

  <branch> denotes the branch that was built, e.g. "master" or "2.9.x".
EOM
  exit 1
}

branch="$1"


[[ -d dists/archives ]] || {
  echo "Can't find build, has it completed? No directory at dists/archives"
  exit 1
}

# Archive Scala nightly distribution
rsync -az dists/archives/ "$nightly_rsync_dest/distributions"

# publish scaladoc nightlies if we are in the master branch
[[ $branch == "master" ]] && rsync -az build/scaladoc/ "$nightly_rsync_dest/docs"

# publish sbaz packages
[[ -d dists/sbaz ]] && rsync -az dists/sbaz/ "$nightly_rsync_dest/sbaz"
