#!/bin/bash -x

artifactoryPasswd=$1

revision=`git rev-parse HEAD`

if [[ ! -z $artifactoryPasswd ]]; then
    echo "Deploying artifacts to typesafe.artifactoryonline.com ..."
    settingsFile=$(mktemp -t mavencredentialsXXX)
    echo "<servers>"                                >  $settingsFile
    echo "<server>"                                 >> $settingsFile
    echo "<id>artifactory-bot</id>"                 >> $settingsFile
    echo "<username>buildbot</username>"            >> $settingsFile
    echo "<password>$artifactoryPasswd</password>"  >> $settingsFile
    echo "</server>"                                >> $settingsFile
    echo "</servers>"                               >> $settingsFile
    (cd jenkins-artifacts/dists/maven/latest && ant -Dremote.snapshot.repository=http://typesafe.artifactoryonline.com/typesafe/scala-pr-validation-snapshots/ -Drepository.credentials.id=artifactory-bot -Dsettings.file="$settingsFile" deploy)
    rm $settingsFile
fi
