#!/bin/bash -ex

# STEP 1: INITIALIZE
script_dir="$( cd "$( dirname "$0" )" && pwd )"
scriptsDir="$( cd "$( dirname "$0" )/../.." && pwd )"
. $scriptsDir/common
runSbt () {
  sbt -Dmaven.settings.file="$maven_settings_file" -no-colors -no-share -sbt-launch-dir "$script_dir/project/launcher" "$@"
}
git clean -dfx
if [[ -d paradise ]]; then rm -rf paradise; fi
git clone git@github.com:scalamacros/paradise.git -b 2.10.3-RC1 paradise
if [[ -d scala ]]; then rm -rf scala; fi
git clone git@github.com:scala/scala.git -b 2.10.x scala

# STEP 2: RUN THE TESTS
cd "$script_dir/paradise"
runSbt "project tests" test
plugin=( $(pwd)/plugin/target/scala-2.10/macro-paradise_*.jar )
[[ ! -f "$plugin" ]] && exit 1

# STEP 4: PUBLISH TO SONATYPE
cd "$script_dir/paradise"
runSbt "project macro-paradise" publish
