#!/bin/bash -ex

# STEP 1: INITIALIZE
script_dir="$( cd "$( dirname "$0" )" && pwd )"
scriptsDir="$( cd "$( dirname "$0" )/../.." && pwd )"
. $scriptsDir/common
runSbt () {
  sbt -Dmaven.settings.file="$maven_settings_file" -Dscala.version="2.10.4" -no-colors -no-share "$@"
}
git clean -dfx
if [[ -d pickling ]]; then rm -rf pickling; fi
git clone git@github.com:scala/pickling.git pickling
cd pickling
git checkout 0.9.x

jar="quasiquotes_2.10-2.0.0.jar"
url="http://search.maven.org/remotecontent?filepath=org/scalamacros/quasiquotes_2.10/2.0.0/quasiquotes_2.10-2.0.0.jar"

http_code=$(curl --fail --silent --output "$jar" "$url")
if (( $? != 0 )); then
  echo "Error downloading $jar: response code: $http_code"
  echo "$url"
  exit 1
fi

# STEP 2: RUN THE TESTS
runSbt "project scala-pickling" test

# STEP 3: PUBLISH TO SONATYPE
runSbt "project scala-pickling" publish
