#!/bin/bash -x
#
# filename format is (currently) "scala-2.10.0-20120523-152645-cdd9845a5e-devel-docs.txz"

DIR=/home/linuxsoft/archives/scala/nightly

# Delete old nightly build files
DIR="${DIR%/}"
find "${DIR}"/*/* -mtime +21 | xargs rm -rf

PAT='-[0-9]{8}-[0-9]+-[0-9a-f]+'
PAT2='-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-+([0-9])-+([0-9a-f])'

# delete old 'latest' links
find "${DIR}" -name '*.latest.*' -type l | xargs rm -rf

shopt -s extglob
update() {
  for ii in $(find "${DIR}" -regextype posix-extended -regex '.*'$PAT'.*?'".$1" |\
              sed -Ee 's/'"${PAT}(.*?).${1}"'/^\1/' | sort -u)
  do
    i=$(ls -t ${ii%\^*}${PAT2}${ii#*\^}.$1 | head -n1)
    ln -sf $i ${ii%\^*}-latest${ii#*\^}.$1
  done;
}

update "zip"
update "tgz"
update "txz"
update "sbp"
update "advert"