#!/bin/bash -ex
# PRE:
#  - artifacts: versions.properties (parsed for maven_version_number)
#  - on pr maven repo: Scala version $maven_version_number
# OPTIONAL ENV VARS: 
#  - $testExtraArgs for any extra arguments to pass to ant
#  - $testTarget (default is test-opt)

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"
. $scriptsDir/common
. $scriptsDir/pr-scala-common

parse_properties versions.properties

cd $WORKSPACE/scala

./pull-binary-libs.sh || ./pull-binary-libs

# build quick using STARR built by pr-scala-publish-core (in that sense it's locker, since it was built with starr by that upstream job)
antArgs="-Dextra.repo.url=$prRepoUrl -Dstarr.version=$maven_version_number -Dlocker.skip=1 -Dstarr.use.released=1"
ant $antArgs $testExtraArgs ${testTarget-"test-opt"}
