#!/bin/bash -ex
# PRE:
#  - vars: sha
#  - artifacts: versions.properties (parsed for maven_version_number, version_minor)
#  - on pr maven repo: Scala version $maven_version_number

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"
. $scriptsDir/common
. $scriptsDir/pr-scala-common
parse_properties versions.properties

if [ "$version_minor" = "12" ]
    then echo "Not integrating with Scala 2.$version_minor."; exit 0
    else echo "Integrating with Scala 2.$version_minor"
fi

BASEDIR=`pwd`
UBERBUILD_URL="https://github.com/scala-ide/uber-build.git"
UBERBUILD_DIR="$BASEDIR/uber-build/"

cd $BASEDIR

#####################################################
# Clone repos
#####################################################

if [[ -d $UBERBUILD_DIR ]]; then
  ( cd $UBERBUILD_DIR && git fetch $UBERBUILD_URL HEAD && git checkout -f FETCH_HEAD && git clean -fxd )
else
  git clone $UBERBUILD_URL
fi

if [ "$version_minor" = "10" ]
    then echo "Using Scala 2.10-specific config file."; CONFIG_FILE_NAME="validator-2.10.conf"
    else echo "Using default config file."; CONFIG_FILE_NAME="validator.conf"
fi

# pass prRepoUrl in, which uber-build passes along to dbuild (in sbt-builds-for-ide)
# the "-P pr-scala" maven arg accomplishes the same thing for maven (directly used in uber-build)
prRepoUrl="$prRepoUrl"\
  MAVEN_ARGS="-P pr-scala"\
    $UBERBUILD_DIR/uber-build.sh $UBERBUILD_DIR/config/$CONFIG_FILE_NAME $sha $maven_version_number

# uber-build puts its local repo under target/m2repo
# wipe the org/scala-lang part, which otherwise just keeps
# growing and growing due to the -$sha-SNAPSHOT approach
[[ -d $WORKSPACE/target/m2repo/org/scala-lang ]] && rm -rf $WORKSPACE/target/m2repo/org/scala-lang

# this assumes ~/.m2/settings.xml contains
# <profile>
#   <id>pr-scala</id>
#   <repositories>
#     <repository>
#       <id>pr-snapshots</id>
#       <name>Scala PR validation snapshots</name>
#       <url>$prRepoUrl</url>
#     </repository>
#   </repositories>
# </profile>
