#!/bin/bash -e
# PRE:
#  - artifacts: versions.properties (parsed for maven_version_number, version_minor)
#  - on pr maven repo: Scala version $maven_version_number

####################################################################
# Build the whole chain from Scala (presumably downloaded from     #
# artifactory) to Scala-IDE, cloning or fetching checkouts of the  #
# elements of said chain in $BASEDIR.                              #
####################################################################

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"
. $scriptsDir/common
. $scriptsDir/pr-scala-common
parse_properties versions.properties

#####################
# BEGIN MAIN SCRIPT #
#####################

main

PARTESTDIR="$BASEDIR/scala-partest/"
PARTESTURL="https://github.com/scala/scala-partest.git"

cd $BASEDIR

#####################################################
# Clone repos
#####################################################

# this depends on the fact that the default clone checkout is the
# dev branch (master or the local equivalent)
getOrUpdate $PARTESTDIR $PARTESTURL "v1.0-RC4" # TODO: replace by "v${partest.version.number}" when that variable is set

#####################################################
# Set versions
#####################################################

if [ "$version_minor" = "11" ]
    then echo "Integrating with Scala 2.11."
    else echo "Not integrating with older Scala."; exit 0
fi

#####################################################
# Prepare SBT
#####################################################

preparesbt

#####################################################
# Build and test partest
#####################################################

curl -o $BASEDIR/sbt-launch.jar -s http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.0/sbt-launch.jar

SBT_JAVA_OPTS="-XX:MaxPermSize=384m -Xmx4096M -XX:+CMSClassUnloadingEnabled -XX:ReservedCodeCacheSize=256m -Dsbt.global.base=$SBT_HOME -Dsbt.ivy.home=$IVY_CACHE -Dsbt.log.noformat=true -jar $BASEDIR/sbt-launch.jar"

(cd $PARTESTDIR &&
 java $SBT_JAVA_OPTS "reboot full" clean "set every scalaVersion := \"$maven_version_number\"" "show scala-instance" publish-local)

# Remove .sbt/repositories scaffolding
#cleanupsbt
