#!/bin/bash -e

####################################################################
# Build the whole chain from Scala (presumably downloaded from     #
# artifactory) to Scala-IDE, cloning or fetching checkouts of the  #
# elements of said chain in $BASEDIR.                              #
####################################################################

scriptsDir="$( cd "$( dirname "$0" )" && pwd )"
. $scriptsDir/../pr-scala-common

#####################
# BEGIN MAIN SCRIPT #
#####################

main

PARTESTDIR="$BASEDIR/scala-partest/"
PARTESTURL="https://github.com/scala/scala-partest.git"

cd $BASEDIR

mkdir -p scala/dists/maven
cp build.number scala/
tar -C scala/dists/maven -xvz -f maven.tgz

#####################################################
# Clone repos
#####################################################

# this depends on the fact that the default clone checkout is the
# dev branch (master or the local equivalent)
getOrUpdate $PARTESTDIR $PARTESTURL "v1.0-RC4"

#####################################################
# Set versions
#####################################################

set_scala_version

if [ "$SCALAMINOR" = "11" ]
    then echo "Integrating with Scala 2.11."
    else echo "Not integrating with older Scala."; exit 0
fi

#####################################################
# Publish scala
#####################################################

publish_scala

#####################################################
# Prepare SBT
#####################################################

preparesbt

#####################################################
# Build and test partest
#####################################################

curl -o $BASEDIR/sbt-launch.jar -s http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.0/sbt-launch.jar

SBT_JAVA_OPTS="-XX:MaxPermSize=384m -Xmx4096M -XX:+CMSClassUnloadingEnabled -XX:ReservedCodeCacheSize=256m -Dsbt.global.base=$SBT_HOME -Dsbt.ivy.home=$IVY_CACHE -Dsbt.log.noformat=true -jar $BASEDIR/sbt-launch.jar"

(cd $PARTESTDIR &&
 java $SBT_JAVA_OPTS "reboot full" clean "set every scalaVersion := \"$SCALAVERSION-$SCALAHASH-SNAPSHOT\"" "show scala-instance" publish-local)

# Remove .sbt/repositories scaffolding
#cleanupsbt
