#!/bin/bash -x

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"

. $scriptsDir/common

./pull-binary-libs.sh || ./pull-binary-libs

ant test-opt # TODO: add ant target that doesn't run stability test
