#!/bin/bash -x

publish=$1
artifactsDir=$2

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"

antArgs="-Darchives.skipxz=true" $scriptsDir/build
buildState=$?
$scriptsDir/archive-checkin
if [[ $publish == "publish" ]] ; then
  $scriptsDir/publish-checkin $artifactsDir
fi
publishState=$?

# i'm not a bash programmer.
if [[ $buildState == 0  && $publishState == 0 ]] ; then
  exit 0
else
  exit 1
fi
