#!/bin/bash -ex

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"
. $scriptsDir/common

gitClean

JAVA_OPTS="$JAVA_OPTS -Dsbt.log.noformat=true" sbt-10 "set logLevel := Level.Error" clean assembly
chmod a+x badsigs.sh
wgetFile job/scala-nightly-main/$mainBuild/artifact/jenkins-artifacts.tgz
tar xzf jenkins-artifacts.tgz

./badsigs.sh jenkins-artifacs/dists/latest/lib/scala-library.jar
