#!/bin/bash -x

[[ $publish == "true" ]] && {
  wget --no-check-certificate --quiet https://scala-webapps.epfl.ch/jenkins/job/scala-nightly-main/$mainBuild/artifact/jenkins-artifacts.tgz
  tar xzf jenkins-artifacts.tgz

  cd jenkins-artifacts

  # publishes the nightly archives, scaladocs
  ../jenkins-scripts/publish-nightly master

  # push to the maven repository
  cd dists/maven/latest
  ant deploy.snapshot -Dsettings.file=/home/linuxsoft/apps/hudson-maven-settings/settings.xml
}
