#!/bin/bash -ex

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"
. $scriptsDir/common

if [ -d scala ]; then
  cd scala
  git fetch -f origin
  git reset --hard origin/master
  cd ..
else
  git clone git@github.com:scala/scala.git
fi

if [ -d scala-dist ]; then
  cd scala-dist
  git fetch -f origin
  git reset --hard origin/master
  cd ..
else
  git clone git@github.com:scala/scala-dist.git
fi

cd scala
./pull-binary-libs.sh

cd ../scala-dist/documentation

cat >build.properties <<'TheProps'
scala.starr.dir=../../scala
number.file=../../scala/build.number
intro.excludes=**/coercions.*
TheProps
echo "Building pdf files..."
PATH="/home/linuxsoft/bin:$PATH" ant clean build.byexample build.reference build.tutorial

# Publish nightly pdf documentation
[[ $publish == "true" ]] && {
  echo "Copying nightly pdf documentation to $nightly_rsync_dest"
  rsync -az build/*.pdf $nightly_rsync_dest/pdfs
}
