#!/bin/bash -ex

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"
. $scriptsDir/common

[[ $publish == "true" ]] && {
  wgetFile job/scala-nightly-main/$mainBuild/artifact/jenkins-artifacts.tgz
  tar xzf jenkins-artifacts.tgz

  cd jenkins-artifacts

  # publishes the nightly archives, scaladocs
  $scriptsDir/publish-nightly master

  # push to the maven repository
  cd dists/maven/latest
  ant deploy.snapshot -Dsettings.file=$maven_settings_file
}
