#!/bin/bash -x

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"

if java -version 2>&1 | grep -q " 1.7"; then
  git checkout -f origin/java7 && git merge origin/master && $scriptsDir/build
else
  $scriptsDir/build
fi
