#!/bin/bash -x

publish=$1
artifactsDir=$2

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"

antArgs="-Darchives.skipxz=true $additionalAntArgs" $scriptsDir/build $scalacArgs
buildState=$?
$scriptsDir/archive-checkin
if [[ $publish == "publish" ]] ; then
    $scriptsDir/publish-checkin $artifactsDir
fi
publishState=$?

# i'm not a bash programmer.
if (( !($buildState || $publishState) )) ; then
  exit 0
else
  exit 1
fi
