#!/bin/bash -x

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"

# @lukas: not sure why this is needed. without it, the 'pull-binary-libs' script fails (*)
# also, some tools (e.g. whoami) are in /usr/bin when running cygwin manually, but not to the jenkins ssh clien. no idea...
export PATH="/cygdrive/c/cygwin/bin:$PATH"

# even though 'echo $OSTYPE' prints 'cygwin', the environment variable is not set (as revealed by 'env')
export OSTYPE="cygwin"

git config --global core.autocrlf input
$scriptsDir/build

# (*)
# bash.exe: warning: could not find /tmp, please create!
# Access denied - H:/JENKINS/WORKSPACE/TEST/LIB
# File not found - -NAME
# .....
