#!/bin/bash -ex

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"
. $scriptsDir/common

gitClean

sbt -no-colors -no-share -sbt-launch-dir $scriptsDir/../project/launcher "set logLevel := Level.Error" clean assembly
chmod a+x badsigs.sh
wgetFile job/scala-nightly-main/$mainBuild/artifact/jenkins-artifacts.tgz
tar xzf jenkins-artifacts.tgz

./badsigs.sh jenkins-artifacts/dists/latest/lib/scala-library.jar
