#!/bin/bash -ex

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"
. $scriptsDir/common

gitClean

# first run crashes with IncompatibleClassChangeError, Josh is looking into it
# http://stackoverflow.com/questions/1980452/what-causes-java-lang-incompatibleclasschangeerror
sbt -no-colors -no-share -sbt-launch-dir $scriptsDir/../project/launcher clean compile || echo "second try..."
sbt -no-colors -no-share -sbt-launch-dir $scriptsDir/../project/launcher make-dist doc test
