#!/bin/bash
#
# filename format is (currently) "scala-2.8.3.rdev-245-2011-12-19-g3d17295.zip"

# Delete old nightly build files
find /home/linuxsoft/archives/scala/nightly/*/* -mtime +21 | xargs rm -rf

PAT='\.rdev-[0-9]+-[0-9]{4}-[0-9]{2}-[0-9]{2}-g[0-9a-f]+'
PAT2='.rdev-+([0-9])-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-g+([0-9a-f])'

# delete old 'latest' links
find /home/linuxsoft/archives/scala/nightly -name '*.latest.*' -type l | xargs rm -rf

shopt -s extglob
update() {
  for ii in $(find /home/linuxsoft/archives/scala/nightly -regextype posix-extended -regex '.*'$PAT".$1" |\
              sed -Ee 's/'"${PAT}.${1}"'//' | sort -u)
  do
    i=$(ls -t ${ii}${PAT2}.$1 | head -n1)
    ln -sf $i ${ii}.latest.$1
  done;
}

update "zip"
update "tgz"
update "txz"
update "sbp"
update "advert"
