#!/bin/bash -ex

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"
. $scriptsDir/common

# Build 'locker' without "-Yrangepos", because 'starr' might not have the
# latest rangepos fixes.

scalacArgs="-Dscalac.args=\"-Yrangepos\" -Dpartest.scalac_opts=\"-Yrangepos\""

gitClean

./pull-binary-libs.sh

ant -Dscalac.args.optimise=-optimise locker.done
ant $scalacArgs build-opt

# No need to run the stability tests
ant -Dscalac.args.optimise=-optimise $scalacArgs test.suite test.scaladoc
