#!/bin/bash -x

scriptsDir="$( cd "$( dirname "$0" )/.." && pwd )"

# number of minutes to poll the slaves for busyness. if some of the slaves
# are still busy after that time, the script quits.
pollTime=60

# sleep time in minutes
sleepTime=5

# slaves to check for busyness
slaves="lamppc49-a lamppc49-b lamppc49-c"

slaveBusy() {
  infoUrl="https://scala-webapps.epfl.ch/jenkins/computer/$1/api/json"
  res=`curl $infoUrl | $scriptsDir/jsonq .idle | tr -d ' '`
  if [[ $res == "false" ]]; then
    return 0
  else
    return 1
  fi
}

busy=true
while $busy && [[ $pollTime -gt 0 ]]; do
  busy=false
  for s in $slaves; do
    if slaveBusy $s; then
      busy=true
    fi
  done

  if $busy; then
    pollTime=$(($pollTime - $sleepTime))
    sleep $(($sleepTime * 60))
  fi
done


if $busy; then
  echo "slaves still busy, exiting"
  exit 1
else
  echo "no other job running now"
  exit 0
fi
