#!/bin/bash -ex

rsync_dest="scalatest@chara.epfl.ch:/home/linuxsoft/archives/scala/nightly"

if [ -d scala ]; then
  cd scala
  git pull origin master
  cd ..
else
  git clone git@github.com:scala/scala.git
fi

if [ -d scala-dist ]; then
  cd scala-dist
  git pull origin master
  cd ..
else
  git clone git@github.com:scala/scala-dist.git
fi

cd scala
./pull-binary-libs.sh

cd ../scala-dist/documentation

cat >build.properties <<'TheProps'
scala.starr.dir=../../scala
number.file=../../scala/build.number.maven
intro.excludes=**/coercions.*
TheProps
echo "Building pdf files..."
PATH="/home/linuxsoft/bin:$PATH" ant clean build.byexample build.reference build.tutorial

# Publish nightly pdf documentation
[[ $publish == "true" ]] && {
  echo "Copying nightly pdf documentation to $rsync_dest"
  rsync -az build/*.pdf $rsync_dest/pdfs
}
