#!/bin/bash -ex

script_dir="$( cd "$( dirname "$0" )" && pwd )"

runSbt () {
  sbt -no-colors -no-share -sbt-launch-dir $script_dir/project/launcher "$@"
}

git clean -dfx
if [[ -d sbt-example-paradise ]]; then rm -rf sbt-example-paradise; fi
git clone git@github.com:scalamacros/sbt-example-paradise.git sbt-example-paradise
cp out.check sbt-example-paradise/out.check
cd sbt-example-paradise
runSbt compile
runSbt run 2>&1 | tee out.txt
grep "`cat out.check`" out.txt
