#!/bin/bash -ex

script_dir="$( cd "$( dirname "$0" )" && pwd )"

runSbt () {
  sbt -no-colors -no-share -sbt-launch-dir $script_dir/project/launcher "$@"
}

git clean -dfx
if [[ -d sbt-example ]]; then rm -rf sbt-example; fi
git clone git@github.com:scalamacros/sbt-example.git sbt-example
cp out.check sbt-example/out.check
cd sbt-example
runSbt compile
runSbt run 2>&1 | tee out.txt
grep "`cat out.check`" out.txt
