#!/bin/bash -ex

script_dir="$( cd "$( dirname "$0" )" && pwd )"

runSbt () {
  sbt -no-colors -no-share -sbt-launch-dir $script_dir/project/launcher "$@"
}

git clean -dfx
runSbt compile
runSbt run 2>&1 | tee out.txt
grep `cat out.check` out.txt
